syntax = "proto3";
package ledger;

enum AccountType {
  ACCOUNT_TYPE_UNSPECIFIED = 0;
  DEBIT = 1;
  CREDIT = 2;
}

enum BalanceType {
  BALANCE_TYPE_UNSPECIFIED = 0;
  AVAILABLE = 1;
  CURRENT = 2;
  HOLD = 3;
}

message CreateAccountCommand {
  AccountType accounting_type = 1;
  BalanceType balance_type = 2;
  bool allow_overdraft = 3;
}

message CreateAccountRequest {
  CreateAccountCommand command = 1;
}

message CreateAccountResponse {
  uint32 book_id = 1;
}

message OperationEntry {
  uint32 book_id = 1;
  AccountType accounting_type = 2;
  // Minor units. Must be > 0. The DEBIT/CREDIT direction of this specific entry is dictated by accounting_type.
  int64 amount = 3;
  // A string code classifying the ledger entry. Length must be <= 8
  string ledger_code = 4;
}

message FinancialOperationCommand {
  repeated OperationEntry entries = 1;
}

message FinancialOperationRequest {
  FinancialOperationCommand command = 1;
}

message BookBalance {
  uint32 book_id = 1;
  // The current balance of the account in minor units after the operation.
  int64 ending_balance = 2;
}

message FinancialOperationResponse {
  uint64 operation_id = 1;
  uint64 timestamp_ns = 2;
  repeated BookBalance balances = 3;
}

service LedgerService {
  rpc CreateAccount(CreateAccountRequest) returns (CreateAccountResponse);
  rpc ExecuteOperation(FinancialOperationRequest) returns (FinancialOperationResponse);
}
